import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load the data generated by the bash script
df = pd.read_csv("data.csv")

# Calculate the log value: log2(TPM + 1)
df['log_val'] = np.log2(df['Value'] + 1)

normal = df[df['Condition'] == 'Solid Tissue Normal']['log_val']
tumor = df[df['Condition'] == 'Primary Tumor']['log_val']

plt.figure(figsize=(7, 6))

plt.boxplot([normal, tumor], 
            labels=['Solid Tissue Normal', 'Primary Tumor'],
            patch_artist=True)

plt.ylabel("Log2 (TPM + 1)")
plt.title("NKX2-1 Gene Expression")

plt.savefig("nkx2-1_boxplot.png")
print("Graph saved!")